// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxYq3Z8PNSu7KSPQMQ1sTcdSTlhFWGsWQ',
    appId: '1:32399781066:web:898453a802c98804fd9833',
    messagingSenderId: '32399781066',
    projectId: 'practice-4c877',
    authDomain: 'practice-4c877.firebaseapp.com',
    storageBucket: 'practice-4c877.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo1KAop-AQlS_MRcr_qk00DjPTmmTzHdE',
    appId: '1:32399781066:android:c38710fdfbc23ab5fd9833',
    messagingSenderId: '32399781066',
    projectId: 'practice-4c877',
    storageBucket: 'practice-4c877.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7aNaki4RB8d5vdHGUQ99jPjr1h0OzBno',
    appId: '1:32399781066:ios:f728fd92170044e3fd9833',
    messagingSenderId: '32399781066',
    projectId: 'practice-4c877',
    storageBucket: 'practice-4c877.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7aNaki4RB8d5vdHGUQ99jPjr1h0OzBno',
    appId: '1:32399781066:ios:f728fd92170044e3fd9833',
    messagingSenderId: '32399781066',
    projectId: 'practice-4c877',
    storageBucket: 'practice-4c877.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxYq3Z8PNSu7KSPQMQ1sTcdSTlhFWGsWQ',
    appId: '1:32399781066:web:f5107d2b95cc070efd9833',
    messagingSenderId: '32399781066',
    projectId: 'practice-4c877',
    authDomain: 'practice-4c877.firebaseapp.com',
    storageBucket: 'practice-4c877.appspot.com',
  );
}
